name: Build Sphinx Documentation

on:
    push:
        branches:
        - main
        - 2-add-continuous-integration
    pull_request:
        branches:
        - 2-add-continuous-integration

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use `windows-latest` or `macos-latest` if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build the documentation
      run: |
        sphinx-apidoc -o docs/ contourusv/     
        cd docs
        make html
    - name: Upload documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}  # Use your deploy key to push to GitHub Pages
        publish_dir: ./docs/build  # Path to the generated HTML docs
