name: Build Sphinx Documentation

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - 2-add-continuous-integration

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use `windows-latest` or `macos-latest` if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set your preferred Python version

    - name: Add src to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme
        # Install missing dependencies
        pip install opencv-python numpy pandas
        pip install tqdm scipy
        pip install matplotlib
        pip install codecarbon

    - name: Build the documentation
      run: |
        # Generate reStructuredText files from the source code
        sphinx-apidoc -o sphinx/ contourusv/ -f

        rm -rf docs/
          
        # Ensure the docs directory exists
        mkdir -p docs

        # Build the HTML documentation
        sphinx-build -b html sphinx/ docs/
        pwd
        ls

        # Add a .nojekyll file to bypass Jekyll processing on GitHub Pages
        touch ./docs/.nojekyll

    - name: Commit and push generated docs
      run: |
        ls
        git config --global user.email "dw42@email.sc.edu"
        git config --global user.name "Dallas Wade"
        git config --global pull.rebase false  # Or true, or --ff-only based on your preference
  
        git add docs/
        git commit -m "Updated docs"
  
        # Ensure gh-pages branch exists and switch to it
        git checkout --orphan gh-pages
        git checkout gh-pages
  
        rm -rf docs/*

        # Ensure docs/ is staged properly
        git add *
        git status  # Debugging: See if anything is staged
        git commit -m "Update Sphinx documentation" || echo "No changes to commit."
  
        # Push the changes
        git push origin gh-pages
  
        # Switch back to main and remove docs from the main branch
        git checkout main
        rm -rf docs/
        git add -A
        git commit -m "Remove docs folder from main branch" || echo "No changes to commit."
        git push origin main
  