name: Build Sphinx Documentation

on:
    push:
        branches:
        - main
        - 2-add-continuous-integration
    pull_request:
        branches:
        - 2-add-continuous-integration

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use `windows-latest` or `macos-latest` if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build the documentation
      run: |
        sphinx-apidoc -o docs/ src/     
        cd docs
        make html

    - name: Deploy to GitHub Pages
      run: |
            git checkout --orphan gh-pages
            git rm -rf .
            cp -r docs/_build/html/* .
            git add .
            git commit -m "Deploy docs"
            git push origin gh-pages --force
            

