name: Build Sphinx Documentation

on:
    push:
        branches:
        - main
        - 2-add-continuous-integration
    pull_request:
        branches:
        - 2-add-continuous-integration

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use `windows-latest` or `macos-latest` if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build the documentation
      run: |
        sphinx-apidoc -o docs/ src/     
        sphinx-build -b html docs/ docs/build/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
